### PR TITLE
removing trailing 0 from cnfgen calls

### PR DESCRIPTION
**Pull request by andertavares**
Hi, I'm using cnfgen installed from pip. If I try to run a data generation script for kcolor (e.g. scripts/generate_kcolor.sh) I get error messages from cnfgen: "c ERROR: unrecognized arguments: 0". 

The problem is solved if the trailing 0 argument is removed from cnfgen calls.

### CODE REVIEW

**Comment by emreyolcu** [comment]
When encoding coloring, cnfgen by default adds axioms which state that each vertex should have at most one color, that is, it requires the coloring map to be a single-valued function. It also does not give an option to disable this from the command-line interface. I used Daniel Selsam's fork (https://github.com/dselsam/cnfgen) which parses the additional argument you noticed and skips said clauses if this argument is `0` (see here: https://github.com/dselsam/cnfgen/commit/45aebb4db3e4dc708ec00492a31f6fb96583d536#diff-54a6be9dbb4d5bdb8b360ec781a0bad2R171).

I would recommend using his fork, otherwise the code with your modification will still run without errors but the coloring formulas will have the difference I mentioned above.

**Comment by andertavares** [comment]
Hi, thanks for the timely response and explanation.

It would be nice to have the fork code added in `code/cnfgen` dir, or to have these instructions be present on the Readme.md. May I add one of these in a new PR? (which one would you prefer?)

[EDIT] Now I noticed that it is just a matter of using the submodules with `git submodule init && git submodule update`. Perhaps adding this little instruction to the Readme would be helpful :).

**Comment by emreyolcu** [comment]
Apparently I broke the training code in a few places while producing the analysis results in Section 7.1 of the paper. I fixed the errors (also resolving #1, #2, #3) and added a README with instructions. Let me know if you run into more issues.

**Comment by andertavares** [comment]
Thanks a lot!

I closed issues #2 and #3 . I'm now able to run train_search.py.  

I only faced a minor problem because of the data directory names. `scritps/generate_kcolor.sh` creates `data/kcolor/4-15.0.5/` and `data/kcolor/5-20.0.5/` (two last commands) but the expected ones are `data/kcolor/4-15-0.5/` and `data/kcolor/5-20-0.5/` (dash rather than dot after 15 and 20).

**Comment by emreyolcu** [comment]
Make sure you checked out the master, because those two lines should already be fixed in the version you get after cloning a fresh repository.

**Comment by andertavares** [comment]
You're right, the file is correct in the repo (https://github.com/emreyolcu/sat/blob/master/scripts/generate_kcolor.sh). The hiccup is on my end, sorry for that.

[EDIT] Now I remember what happened: I uas running the new code with data generated with the "old" code, hence the directories were that way.

**Pull request closed without merging**
